project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls'))
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    #path('', views.index, name='index'),
    #path('bug_list/', views.bug_list, name='bug_list'),
    #path('bug_list/<id>/', views.bug_detail, name='bug_detail'),
    #path('feature_list/', views.feature_list, name='feature_list'),
    #path('feature_list/<id>/', views.feature_id_detail, name='feature_id_detail')
    path('', views.IndexView.as_view(), name='index'),

    path('bug_list/', views.BugsListView.as_view(), name='bug_list'),
    path('bug_list/<id>/', views.BugsDetailView.as_view(), name='bug_detail'),
    path('feature_list/', views.FeatureListView.as_view(), name='feature_list'),
    path('feature_list/<id>/', views.FeatureDetailView.as_view(), name='feature_detail'),

    path('bug_list/add_bug/', views.BugReportCreateView.as_view(), name='create_bug'),
    path('feature_list/add_feature/', views.FeatureRequestCreateView.as_view(), name='create_feature'),

    path('bug_list/<bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bug'),
    path('bug_list/<bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bug'),
    path('feature_list/<feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_feature'),
    path('features_list/<feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_feature'),
]

tasks/urls.py
from django.urls import path, include
from tasks import views

app_name = 'tasks'

urlpatterns = [
    #path('', views.index),
    #path('quality_control/', include('quality_control.urls'), name='qual'),
    #path('projects/', views.projects_list, name='projects_list'),
    #path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    #path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    #path('quality_control/', include('quality_control.urls'), name='qual'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE
    )
    priority = models.IntegerField(
        default=3,
        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New'
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE
    )
    priority = models.IntegerField(
        default=3,
        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New'
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

quality_control/forms.py
from django.forms import ModelForm

from .models import BugReport, FeatureRequest


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'project', 'task', 'priority','status']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'project', 'task', 'priority', 'status']

quality_control/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import BugReport, FeatureRequest
from .forms import BugReportForm, FeatureRequestForm


def index(request):
    return render(request, 'quality_control/index.html')


def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list': bugs})


def bug_detail(request, id: str):
    bug = get_object_or_404(BugReport, id=id)
    return render(request, 'quality_control/bug_list.html', {'bug': bug})


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list': features})


def feature_detail(request, id: str):
    feature = get_object_or_404(FeatureRequest, id=id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


class BugsListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'
    context_object_name = 'bug_list'


class BugsDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'id'
    template_name = 'quality_control/bug_detail.html'
    context_object_name = 'bug'


class FeatureListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'
    context_object_name = 'feature_list'


class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'id'
    template_name = 'quality_control/feature_detail.html'
    context_object_name = 'feature'


def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_create.html'
    success_url = reverse_lazy('quality_control:bug_list')


class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_create.html'
    success_url = reverse_lazy('quality_control:feature_list')


def update_bug_report(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id)

    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'bug': bug})


def update_feature_request(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id)

    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_request_update.html', {'form': form, 'feature': feature})


class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')


class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')


def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bug_list')


def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')


class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')
    template_name = 'quality_control/bug_confirm_delete.html'


class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    template_name = 'quality_control/feature_confirm_delete.html'
# def index(request):
#    bug_list_request = reverse('quality_control:bug_list')
#   feuture_list_request = reverse('quality_control:feature_list')
#  html = "<h1>Система контроля качества</h1><a href=" + "'" + str(
#     bug_list_request) + "'" + ">Cписок всех багов</a><p><a href=" + "'" + str(
#    feuture_list_request) + "'" + ">Запросы на улучшение</a></p>"
# return HttpResponse(html)
# def bug_detail(request, id: str):
#    return HttpResponse("<p>Детали бага " + id + "</p>")


# def feature_list(request):
#   return HttpResponse("<h1>Список запросов на улучшение</h1>")


# def feature_id_detail(request, id: str):
#    return HttpResponse("<p>Детали улучшения " + id + "</p>")

quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчета о баге</h1>
    <p>Вы уверены, что хотите удалить отчет о баге "{{ object.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' object.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' object.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ bug.title }}</h1>
    <p>{{ bug.description }}</p>
    <h2>Статус бага</h2>
    <p>{{ bug.status }}</p>
{% endblock %}

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список отчетов об ошибках</h1>
    <ul>
        {% for bug in bug_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить отчет о баге</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать отчет</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчета об ошибке: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение бага: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить этот запрос на улучшение "{{ object.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' object.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' object.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_create.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новое предложение об улучшении</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ feature.title }}</h1>
    <p>{{ feature.description }}</p>
    <h2>Статус улучшения</h2>
    <p>{{ feature.status }}</p>
{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <ul>
        {% for feature in feature_list %}
            <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить предложение об улучшении</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать предложение об улучшении</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение проекта: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Страница приложения quality_control</h1>
    <a href="{% url 'quality_control:bug_list' %}">Cписок всех багов</a>
    <p><a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a></p>
{% endblock %}